### ISSUE TITLE
Support for Applications

### ISSUE THREAD

**Issue by nilesh-atal** [IBM-Verify/verifyctl#30]
**Is your feature request related to a problem? Please describe.**
Verifyctl tool should have support for CRUD operations of Applications

**Describe the solution you'd like**
The tool should be able to create/update/delete applications. It should provide a command to generate different input configuration based on type of application to be created. The various types supported as SAML, OIDC, BOOKMARK, ACLC

```
verifyctl.exe create application --applicationType=bookmark --boilerplate
```
The output of above command should provide a YAML payload which should be used to create Application
```
kind: IBMVerifyApplications
apiVersion: "1.0"
metadata: null
data:
  name: ""
  templateId: ' '
  providers:
    sso:
      userOptions: 'applicationBookmark'
      idpInitiatedSSOSupport: 'false'
    saml:
      properties:
        companyName: ' '
    bookmark:
      bookmarkUrl: ' '
  provisioning:
    attributeMappings: []
    policies:
      adoptionPolicy:
        remediationPolicy:
          policy: NONE
      provPolicy: disabled
      deProvPolicy: disabled
      deProvAction: delete
      gracePeriod: 1
    reverseAttributeMappings: []
  attributeMappings: []
  applicationState: true
  description: ' '
  visibleOnLaunchpad: true
  apiAccessClients: []
``` 

```
verifyctl.exe create application --applicationType=saml --boilerplate
```
The output of above command should provide a YAML payload which should be used to create Application
```
kind: IBMVerifyApplications
apiVersion: "1.0"
metadata: null
data:
  name: ""
  templateId: ' '
  providers:
    sso:
      userOptions: 'saml'
      domainName: ' '
    saml:
      justInTimeProvisioning: 'false'
      properties:
        companyName: ' '
        generateUniqueID: 'false'
        validateAuthnRequest: 'false'
        encryptAssertion: 'false'
        ici_reserved_subjectNameID: ' '
        includeAllAttributes: 'true'
        providerId: ' '
        assertionConsumerServiceUrl: ' '
        uniqueID: ' '
  provisioning:
    attributeMappings: []
    policies:
      adoptionPolicy:
        remediationPolicy:
          policy: NONE
      provPolicy: disabled
      deProvPolicy: disabled
      deProvAction: suspend
      gracePeriod: 1
    reverseAttributeMappings: []
  attributeMappings: []
  applicationState: true
  description: ' '
  visibleOnLaunchpad: true
  apiAccessClients: []
  target:
    connectedApp_DataDotcom: false
    connectedApp_SalesforceChatter: true
    connectedApp_SalesforceSalesCloud: false
    connectedApp_SalesforceServiceCloud: false
```

```
verifyctl.exe create application --applicationType=aclc --boilerplate
```
The output of above command should provide a YAML payload which should be used to create Application
```
kind: IBMVerifyApplications
apiVersion: "1.0"
metadata: null
data:
  name: ' '
  templateId: ' '
  providers:
    sso:
      domainName: ' '
      userOptions: ' '
    saml:
      justInTimeProvisioning: 'false'
      properties:
        companyName: ' '
    bookmark:
      bookmarkUrl: ' '
  provisioning:
    extension:
      properties:
        endpointBaseUrl: ' '
    attributeMappings:
      - targetName: ' '
        sourceId: ' '
        outboundTracking: true
    policies:
      adoptionPolicy:
        matchingAttributes:
          - targetName: ' '
            sourceId: ' '
        remediationPolicy:
          policy: NONE
      provPolicy: automatic
      deProvPolicy: automatic
      deProvAction: delete
    sendNotifications: true
    reverseAttributeMappings:
      - targetName: ' '
        sourceId: ' '
        outboundTracking: true
    authentication:
      properties:
        client_id: ' '
        pwd_client_secret: ' '
  attributeMappings: []
  applicationState: true
  description: ' '
  visibleOnLaunchpad: true
  apiAccessClients: []
```

```
verifyctl.exe create application --applicationType=oidc --boilerplate
```
The output of above command should provide a YAML payload which should be used to create Application
```
kind: IBMVerifyApplications
apiVersion: "1.0"
metadata: null
data:
  name: ""
  templateId: ' '
  providers:
    sso:
      userOptions: oidc
    saml:
      properties:
        companyName: ' '
        uniqueID: ' '
    oidc:
      properties:
        grantTypes:
          authorizationCode: true
          implicit: true
          deviceFlow: true
          ropc: true
          jwtBearer: true
          policyAuth: true
          clientCredentials: true
          tokenExchange: true
        redirectUris:
          - ' '
          - ' '
        idTokenSigningAlg: RS256
        accessTokenExpiry: 1
        refreshTokenExpiry: 1
        doNotGenerateClientSecret: 'false'
        generateRefreshToken: 'false'
        renewRefreshToken: 'true'
        idTokenEncryptAlg: none
        idTokenEncryptEnc: none
        additionalConfig:
          oidcv3: true
          requestObjectParametersOnly: 'false'
          requestObjectSigningAlg: RS256
          requestObjectRequireExp: 'true'
          certificateBoundAccessTokens: 'false'
          dpopBoundAccessTokens: 'false'
          validateDPoPProofJti: 'false'
          dpopProofSigningAlg: RS256
          authorizeRspSigningAlg: RS256
          authorizeRspEncryptionAlg: none
          authorizeRspEncryptionEnc: none
          responseTypes:
            - none
            - code
          responseModes:
            - query
            - fragment
            - form_post
            - query.jwt
            - fragment.jwt
            - form_post.jwt
          clientAuthMethod: default
          requirePushAuthorize: 'false'
          requestObjectMaxExpFromNbf: 1
          exchangeForSSOSessionOption: default
          subjectTokenTypes:
            - urn:ietf:params:oauth:token-type:access_token
          actorTokenTypes:
            - urn:ietf:params:oauth:token-type:access_token
          requestedTokenTypes:
            - urn:ietf:params:oauth:token-type:access_token
          actorTokenRequired: true
          logoutOption: none
          sessionRequired: true
          requestUris:
            - ' '
          allowedClientAssertionVerificationKeys:
            - ' '
            - ' '
      grantProperties:
        generateDeviceFlowQRCode: 'false'
      token:
        accessTokenType: default
        audiences:
          - ' '
      applicationUrl: ' '
      restrictEntitlements: true
      consentAction: always_promt
      requirePkceVerification: 'true'
  provisioning:
    attributeMappings: []
    reverseAttributeMappings: []
  attributeMappings: []
  applicationState: true
  description: ' '
  visibleOnLaunchpad: true
  apiAccessClients: []
```

**It should support other operations as CREATE / GET / REPLACE / DELETE:**
Create Application 
```
verifyctl create -f "application.yaml"
```

Update Application 
```
verifyctl replace -f "application.yaml"
```

Delete Application 
```
verifyctl delete application --applicationId "xxxxx-xxxxxx-xxxxxxx-xxxxx"
```

Get all Applications 
```
verifyctl get applications
```

Get Application by Id 
```
verifyctl get application --applicationId "xxxxx-xxxxxx-xxxxxxx-xxxxx"
```

**Additional context**
NA
